
name: Clone Repository

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Move file to folder
      run: sudo cp test_job_jenkins.py /home/ubuntu/glue-script/

    - name: Run the destination
      run: python3 /home/ubuntu/glue-script/glue_script.py
